ESP/cda/urls.py
'''
                              ESP Health Project
User Interface Module
                               URL Configuration

@authors: Jay Boyer <jboyer@commoninf.com>
'''

from django.urls import include, re_path
from ESP.cda import views

urlpatterns = [
    re_path(r'^$', views.post),   
]

ESP/coc/urls.py
from django.urls import re_path
from ESP.coc import views

app_name = 'coc'

urlpatterns =[
    re_path(r'^linelist/$', views.linelist, name='linelist'),
]

ESP/hiv_risk/urls.py
# -*- coding: utf-8 -*-

from django.urls import include, re_path
from django.conf.urls import include
from ESP.hiv_risk import views
from django.urls import path

app_name = 'hiv_risk'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^report/view/(?P<patient_id>\d+)/$', views.hrp_detail, name='hrp_detail'),
    re_path(r'^report/$', views.report, name='report'),
    re_path(r'^show_file/$', views.show_file, name='show_file'),
    re_path(r'ad_hoc_disposition/$', views.ad_hoc_dispo, name='ad_hoc_disposition'),
    re_path(r'^ad_hoc_disposition/view/(?P<patient_id>\d+)/$', views.hrp_history_detail, name='hrp_history_detail'),
]

ESP/ui/urls.py
'''
                              ESP Health Project
User Interface Module
                               URL Configuration

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2010 Channing Laboratory
@license: LGPL
'''


from django.urls import include, re_path
from ESP.ui import views

urlpatterns = [
    re_path(r'^labtest/lookup/$', views.labtest_lookup, name='labtest_lookup'),
    re_path(r'^labtest/detail/$', views.labtest_detail, name='labtest_detail'),
    re_path(r'^labtest/linelist/(?P<native_code>.*)$', views.labtest_csv, name='labtest_csv'),
    re_path(r'^labtest/linelist/(?P<native_code>.*)$', views.labtest_csv, name='labtest_csv'),
    re_path(r'^labtest/ignore_set/$', views.ignore_code_set, name='ignore_code_set'),
    re_path(r'^labtest/map/(?P<native_code>.+)/$', views.map_native_code, name='map_native_code'),
    re_path(r'^labtest/unmapped/$', views.unmapped_labs_report, name='unmapped_labs_report'),
    re_path(r'^labtest/unmapped/(?P<condition>[\w\s]+)/$', views.unmapped_labs_report, name='condition_unmapped_labs_report'),
    #
    #-------------------------------------------------------------------------------
    # Nodis
    #-------------------------------------------------------------------------------
    #
    re_path(r'^cases/$', views.case_list, {'status': 'all'}, name='nodis_cases_all'),
    re_path(r'^cases/list/awaiting_review/$', views.case_list, {'status': 'await'}, name='nodis_cases_awaiting_review'),
    re_path(r'^cases/list/under_review/$', views.case_list, {'status': 'under'}, name='nodis_cases_under_review'),
    re_path(r'^cases/list/queued/$', views.case_list, {'status': 'queued'}, name='nodis_cases_queued'),
    re_path(r'^cases/list/sent/$', views.case_list, {'status': 'sent'}, name='nodis_cases_sent'),
    re_path(r'^cases/list/requeued/$', views.case_list, {'status': 'requeued'}, name='nodis_cases_requeued'),
    #
    # Case Detail
    #
    re_path(r'^cases/view/(?P<case_id>\d+)/$', views.case_detail, name='nodis_case_detail'),
    re_path(r'^cases/viewpert/(?P<case_id>\d+)/$', views.pertussis_detail, name='nodis_pertussis_detail'),
    re_path(r'^cases/update/(?P<case_id>\d+)/$', views.case_status_update, name='nodis_case_update'),
    re_path(r'^cases/transmit/(?P<case_id>\d+)/$', views.case_queue_for_transmit, name='nodis_case_transmit'),
    re_path(r'^provider/(?P<provider_id>\w+)/$', views.provider_detail, name='provider_detail'),
    re_path(r'^patient/(?P<patient_pk>\d+)/records/$', views.all_records, name='all_records'),
    #
    # Validator
    #
    re_path(r'^validate/$', views.validator_summary, name='validator_summary'),
    re_path(r'^validate/missing/$', views.validate_missing, name='validate_missing'),
    re_path(r'^validate/missing/case/(?P<result_id>\d+)/$', views.missing_case_detail, name='missing_case_detail'),
    re_path(r'^validate/new/$', views.validate_new, name='validate_new'),
    re_path(r'^validate/similar/$', views.validate_similar, name='validate_similar'),
    re_path(r'^validate/exact/$', views.validate_exact, name='validate_exact'),

]

ESP/urls.py
'''
URLs for entire ESP Health django project
'''
from django.urls import include, re_path
from django.conf.urls import include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView, LoginView
from ESP.settings import MEDIA_ROOT
from ESP.ui.views import status_page
from ESP.ui.views_survey import generate_survey_report, view_survey_report, survey_import
from django.views import static

class ExtraContextTemplateView(TemplateView):
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super(ExtraContextTemplateView, self).get_context_data(**kwargs)
        if self.extra_context:
            context.update(self.extra_context)
        return context

admin.autodiscover()

urlpatterns = [
    
    # Core Application
    re_path(r'^$', status_page, name='status'),
    
    # Vaers
    re_path(r'^vaers/', include('ESP.vaers.urls')),

    # HIV Risk 
    re_path(r'^hiv_risk/', include('ESP.hiv_risk.urls')),
    
    # Survey 
    re_path(r'^survey_import/', survey_import, name='survey_import'),
    re_path(r'^view_survey_report/', view_survey_report, name='view_survey_report'),
    re_path(r'^generate_survey_report/', generate_survey_report, name='generate_survey_report'),

    # Login and Logout
    #re_path(r'^login/?$', login, {'template_name': 'login.html'}, name='login'),
    #re_path(r'^logout/?$', logout, {'next_page': '/'}, name='logout'),
    re_path(r'^login/?$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    re_path(r'^logout/?$', LogoutView.as_view(), {'next_page': 'logged_out.hml'}, name='logout'),
    
    # About
    re_path(r'^about/', ExtraContextTemplateView.as_view(
        template_name='about.html',
        extra_context={'title': 'About ESP'}
    ), name='about'),
    
    
    # Django Admin
    re_path(r'^admin/', admin.site.urls),
#   (r'^admin/doc/', include('django.contrib.admindocs.urls'),

    re_path(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT}),
    
    # Configuration
    re_path(r'^conf/', include('ESP.conf.urls')),
    
    # Nodis
    #re_path(r'^nodis/', include('ESP.nodis.urls')),
    
    # Nodis
    re_path(r'^util/', include('ESP.ui.urls')),

    # cda_input
    re_path(r'^cda/', include('ESP.cda.urls')),

    # Continuity of Care
    re_path(r'^coc/', include('ESP.coc.urls')),

    #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #
    #re_path(r'^codes', code_maintenance),
    #re_path(r'^json_code_grid', json_code_grid, name='json_code_grid'),
    #re_path(r'^/$', include('ESP.ui.urls')),
]

ESP/vaers/urls.py
# -*- coding: utf-8 -*-

from django.urls import include, re_path

from ESP.vaers import views

app_name = 'vaers'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^casetable$', views.list_cases),
    re_path(r'^notify/(?P<id>\d+)/$', views.notify),
    re_path(r'^report$', views.report, name='report'),

    # Vaccine and Manufacturer Mapping
    re_path(r'^vaccines/', include('ESP.vaers.vaccine.urls')),
    
    # ptype can be digest or case.  digest takes a digest value for id, case takes a questionnaire id for id.
    re_path(r'^(?P<ptype>case|digest)/(?P<id>\w*)/$', views.case_details, name='present_case'),

    #line listing report
    re_path(r'^download/', views.download_vae_listing, name='download_listing'),    
]


ESP/cda/models.py
from django.db import models

# Create your models here.

ESP/conf/forms.py
'''
                              ESP Health Project
                             Configuration Module
                              User Interface Forms


@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


from django import forms


class CodeMappingForm(forms.Form):
    '''
    Form for mapping Native Code to LOINC
    '''
    native_name = forms.CharField(max_length=255, required=True)
    native_code = forms.CharField(max_length=100, required=True)

ESP/vaers/vaccine/forms.py
from django import forms

from ESP.conf.models import Vaccine, ImmunizationManufacturer

try:
    STANDARD_VACCINES = ((x.code, str(x)) for x in Vaccine.acceptable_mapping_values())
except:
    STANDARD_VACCINES = []
try:
    STANDARD_MANUFACTURERS = ((x.code, str(x)) for x in ImmunizationManufacturer.objects.all())
except:
    STANDARD_MANUFACTURERS = []

class StandardVaccinesForm(forms.Form):
    vaccine = forms.ChoiceField(choices=STANDARD_VACCINES)

class StandardManufacturersForm(forms.Form):
    manufacturer = forms.ChoiceField(choices=STANDARD_MANUFACTURERS)

ESP/cda/views.py
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.decorators import parser_classes 
from rest_framework.decorators import authentication_classes
from rest_framework.decorators import permission_classes
from rest_framework.response import Response
from rest_framework_xml.parsers import XMLParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from ESP.utils.utils import log
from ESP.settings import DATA_DIR
import datetime

# Create your views here.
@api_view(['POST'])
@parser_classes([XMLParser])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])

def post(request):

    try:
        # verify XML format
        if(request.content_type != 'application/xml'):
            return Response("Only XML accepted, Illegal type: " + request.content_type, 
                status=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE, content_type='text/plain')

        # get the patient id from the header
        patientId = ''
        try:
            patientId = request.META['HTTP_X_PATIENT_ID']
        except Exception as e:
            pass

        if(not patientId or len(patientId) < 6 or patientId.find('-') != -1):
            return Response("Missing or bad patient identifier (minimum length 6, dashes not allowed) 'x-patient-id' in header: [" + patientId +"]", 
                status=status.HTTP_417_EXPECTATION_FAILED, content_type='text/plain')
        
        # write the xml to a file under the data/cda structure
        try:
            file = None
            name = ''
            strXml = request.body.decode().strip()

            # check the contents to make sure at least appears to be XML
            length = len(strXml)
            if(length == 0):
                return Response("0 length file", status=status.HTTP_411_LENGTH_REQUIRED, content_type='text/plain')

            if(length < 5 or strXml[0:5].lower() != "<?xml"):
                return Response("Non-XML data", status=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE, content_type='text/plain')

            # create a file based on the username, current time and patient id
            dt = datetime.datetime.now()
            prefix = request.user.username[:8] + '-'
            log.debug('name:' + request.user.username)
            log.debug('prefix:' + prefix)
            name = prefix + dt.strftime('%Y%m%d-%H%M%S-%f') + '-' + patientId + '.xml'

            file = open(DATA_DIR + 'cda/incoming/' + name, "w")
            file.write(strXml)

        except Exception as e:
            msgErr = 'Exception creating local cda file: ' + name + '\n' + str(e)
            log.error(msgErr)
            return Response(msgErr, status=status.HTTP_417_EXPECTATION_FAILED, content_type='text/plain')
        
        finally:
            if file != None:
                file.close()

        return Response('received data:' + name, status=status.HTTP_200_OK, content_type='text/plain')

    except Exception as e:
        return Response(e.args[0], status=status.HTTP_400_BAD_REQUEST, content_type='text/plain')

ESP/conf/views.py
'''
                              ESP Health Project
Configuration Module
Views

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


import operator

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse
from django.shortcuts import render, redirect
from ESP.conf.models import IgnoredCode
from ESP.conf.models import LabTestMap
from ESP.utils.utils import log
from ESP.hef.base import BaseLabResultHeuristic, PrescriptionHeuristic, DiagnosisHeuristic
from ESP.ui.other_labs import STANDARD_LABS

@login_required
def heuristic_mapping_report(request):
    values = {'title': 'Abstract Lab Mapping Summary'}
    mapped = []
    unmapped = []
    test_names = []
    ## get all test names from heuristics and other labs
    lab_results = BaseLabResultHeuristic.get_all()
    for lrh in BaseLabResultHeuristic.get_all():
        test_names.append(lrh.test_name)
    for sname in STANDARD_LABS:
        if sname not in test_names:
            test_names.append(sname)

    for test_name in test_names: 
        maps = LabTestMap.objects.filter(test_name=test_name)
        if not maps:
            # if unmapped doesnt already have test name then add it
            if not unmapped.__contains__(test_name):
                unmapped.append( (test_name) )
            continue
        codes = maps.values_list('native_code', flat=True)
        # if mapped doesnt already contain (heuristic.test_name, codes) then add it
        # it is sorted already,for each in mapped get item compare with test name 
        # add first one
        if not mapped: mapped.append( (test_name, codes) )
        # loop through mapped make sure is not already there
        else:
            contains=False
            for index in range(len(mapped)):  
                if mapped.__getitem__(index).__contains__((test_name)):
                    contains=True
                    continue
            if not contains: 
                mapped.append( (test_name, codes) )              
        
    mapped.sort(key=operator.itemgetter(0))
    unmapped.sort()
    values['mapped'] = mapped
    values['unmapped'] = unmapped
    return render(request, 'conf/heuristic_mapping_report.html', values)

@login_required
def heuristic_reportables(request):
    values = {'title': 'Heuristic Reportables Summary'}
    
    reportable_rx = []
    reportable_dx = []
    reportable_lx = []
    
    for heuristic in BaseLabResultHeuristic.get_all():
        if heuristic.test_name not in reportable_lx:
            reportable_lx.append(heuristic.test_name)

    for sname in STANDARD_LABS:
        if sname not in reportable_lx:
            reportable_lx.append(sname)

    for heuristic in DiagnosisHeuristic.get_all():
        if isinstance(heuristic, DiagnosisHeuristic):
            for dx_code in heuristic.dx_code_queries:
                if dx_code not in reportable_dx:
                    reportable_dx.append(dx_code)
            
    for heuristic in PrescriptionHeuristic.get_all():
        if isinstance(heuristic, PrescriptionHeuristic):
            for drug in heuristic.drugs:
                if drug not in reportable_rx:
                    reportable_rx.append(drug)
    
    reportable_lx.sort()
    reportable_dx.sort(key=lambda x: x.verbose_name)
    reportable_rx.sort()
    
    values['reportable_lx'] = reportable_lx
    values['reportable_dx'] = reportable_dx
    values['reportable_rx'] = reportable_rx
    
    return render(request, 'conf/heuristic_reportables.html', values)


@user_passes_test(lambda u: u.is_staff)
def ignore_code(request, native_code):
    '''
    Display Unmapped Labs report generated from cache
    '''
    if request.method == 'POST':
        #ic_obj, created = IgnoredCode.objects.get_or_create(native_code=native_code.lower())
        ic_obj, created = IgnoredCode.objects.get_or_create(native_code=native_code) # Why was this lower() before?
        if created:
            ic_obj.save()
            msg = 'Native code "%s" has been added to the ignore list' % native_code
        else:
            msg = 'Native code "%s" is already on the ignore list' % native_code
        messages.add_message(request,messages.INFO,msg)
        log.debug(msg)
        return redirect(reverse('unmapped_labs_report'))
    else:
        values = {
            'title': 'Unmapped Lab Tests Report',
            "request":request,
            'native_code': native_code,
            }
        return render(request, 'conf/confirm_ignore_code.html', values)
    

ESP/templates/about.html
{% extends 'base.html' %}

{% block content %}



<h2>Welcome to the <a href="http://esphealth.org/ESPnet/images/ESP.html">ESP</a> web interface</h2><p>
<p>
The Electronic medical record Support for Public health (ESP) project is an automated software application, that analyzes electronic medical record (EMR) data, to identify and report conditions of interest to public health and other agencies.
<p>
<p>ESP is part of a larger project that includes <a href="http://esphealth.org/ESPnet/images/PopMedNet.html">PopMedNet</a>
<p>
<p>More information is available at <a href="http://esphealth.org">esphealth.org</a>
</p>

{% endblock%}

ESP/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-us" xml:lang="en-us">

<head>
    <title>
        {% if title %}{{ title }} -{% endif %} Electronic medical record Support for Public Health (ESPnet)
    </title>

    <link href="{{ site_css_folder }}base.css" rel="stylesheet" type="text/css"/>

    <link rel="stylesheet" href="{{ site_css_folder }}jquery-ui.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="{{ site_css_folder }}ui.theme.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="{{ site_javascript_folder }}/jdMenu-1.4.1/jquery.jdMenu.css" type="text/css"
          media="all"/>
    <script src="{{ site_javascript_folder }}jquery-1.4.2.js" type="text/javascript"></script>
    <script src="{{ site_javascript_folder }}jquery-ui-1.8.4.js" type="text/javascript"></script>
    <script src="{{ site_javascript_folder }}/jdMenu-1.4.1/jquery.bgiframe.js" type="text/javascript"></script>
    <script src="{{ site_javascript_folder }}/jdMenu-1.4.1/jquery.dimensions.js" type="text/javascript"></script>
    <script src="{{ site_javascript_folder }}/jdMenu-1.4.1/jquery.jdMenu.js" type="text/javascript"></script>
    <script src="{{ site_javascript_folder }}/jdMenu-1.4.1/jquery.positionBy.js" type="text/javascript"></script>
    <script src="{{ site_javascript_folder }}flexigrid/flexigrid.js" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('ul.jd_menu').jdMenu();
        });
    </script>

    {% block extrastyle %}{% endblock %}
    {% block extrascript %}{% endblock %}


</head>

<body>

<div id="header">
	<span id="version_site_user"> 
		<br>
		Version: {{ version }}
        {% if user.is_authenticated %}
            <br>
            Site: {{ site_name }}
            <br>
            User: {{ user }}
        {% endif %}
	</span>

    <h1>
        <img src="{{ site_image_folder }}/caduceus.gif" alt="caduceus" border=0/>

        <span id="main_title">ESP &mdash; Electronic medical record Support for Public Health (ESPnet)</span>
    </h1>
</div>


{% if user.is_authenticated %}
    <div id="navigation">
        <ul class='jd_menu'>
            <li><a href="{% url 'status' %}">Status</a></li>
            {% if show_surveys %}
                <li>Surveys &raquo;
                    <ul>
                        <li><a href="{% url 'survey_import' %}">Import Responses</a></li>
                        <li>Survey Results &raquo;
                            <ul>
                                <li><a href="{% url 'view_survey_report' %}">View Last BRFSS Demo</a></li>
                                <li><a href="{% url 'generate_survey_report' %}">Generate BRFSS Demo</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            {% endif %}
            <li>Nodis &raquo;
                <ul>
                    <li><a href="{% url 'nodis_cases_all' %}">Cases - All</a></li>
                    <li><a href="{% url 'nodis_cases_awaiting_review' %}">Cases - Awaiting Review</a></li>
                    <li><a href="{% url 'nodis_cases_under_review' %}">Cases - Under Review</a></li>
                    <li><a href="{% url 'nodis_cases_queued' %}">Cases - Queued</a></li>
                    <li><a href="{% url 'nodis_cases_sent' %}">Cases - Sent</a></li>
                </ul>
            </li>
            <li><a href="{% url 'vaers:index' %}">Vaers &raquo;</a>
                <ul>
                    <li><a href="{% url 'vaers:vaccine:index' %}">Vaccine Mapping</a></li>
                    <li><a href="{% url 'vaers:vaccine:manufacturers' %}">Manufacturers Mapping</a></li>
                    <li><a href="{% url 'vaers:report' %}">Satscan Clustering Report</a></li>
                    <li><a href="{% url 'vaers:download_listing' %}">Download VAERS Line Listing</a></li>
                </ul>
            </li>
            <li>HIV Risk &raquo;
                <ul>
                    <li><a href="{% url 'hiv_risk:report' %}">Current Patient Linelist</a></li>
		    <li><a href="{% url 'hiv_risk:ad_hoc_disposition' %}">Record Ad Hoc Disposition </a></li>
                </ul>
            </li>

            <li>Administration &raquo;
                <ul>
                    {% if user.is_staff %}
                        <li><a href="{% url 'admin:index' %}">Site Administration</a></li>
                    {% endif %}
                    <li><a href="{% url 'heuristic_mapping_report' %}">Lab Mapping Summary</a></li>
                    <li><a href="{% url 'unmapped_labs_report' %}">Unmapped Lab Tests Report</a></li>
                    <li><a href="{% url 'heuristic_reportables' %}">Heuristic Reportables Summary</a></li>
                    <li><a href="{% url 'validator_summary' %}">Case Validator</a></li>
                    <li><a href="{% url 'labtest_lookup' %}">Lab Test Lookup</a></li>
                </ul>
            </li>
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
{% else %}
    <hr>
{% endif %}

<div id="content">
    <h1 id="title">{{ title }}</h1>

    {% if messages %}
        <div id="messages">
            <ul id="message_list">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    {% block content %}
    {% endblock %}
</div>

</body>

</html>

ESP/templates/login.html
{% extends 'base.html' %}

{% block content %}

    <h1>Please Login</h1>

    <p>Access to this system is limited to authorized persons only.</p>

    {% if form.errors %}
        <p><em>Your username and password didn't match. Please try again.</em></p>
    {% endif %}

    <form method="post" action="{% url 'login' %}">
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="login"/>
        <input type="hidden" name="next" value="{{ next }}"/>
        {% csrf_token %}
    </form>

{% endblock %}