ESP/cda/urls.py
'''
                              ESP Health Project
User Interface Module
                               URL Configuration

@authors: Jay Boyer <jboyer@commoninf.com>
'''

from django.urls import include, re_path
from ESP.cda import views

urlpatterns = [
    re_path(r'^$', views.post),   
]

ESP/coc/urls.py
from django.urls import re_path
from ESP.coc import views

app_name = 'coc'

urlpatterns =[
    re_path(r'^linelist/$', views.linelist, name='linelist'),
]

ESP/ui/urls.py
'''
                              ESP Health Project
User Interface Module
                               URL Configuration

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2010 Channing Laboratory
@license: LGPL
'''


from django.urls import include, re_path
from ESP.ui import views

urlpatterns = [
    re_path(r'^labtest/lookup/$', views.labtest_lookup, name='labtest_lookup'),
    re_path(r'^labtest/detail/$', views.labtest_detail, name='labtest_detail'),
    re_path(r'^labtest/linelist/(?P<native_code>.*)$', views.labtest_csv, name='labtest_csv'),
    re_path(r'^labtest/linelist/(?P<native_code>.*)$', views.labtest_csv, name='labtest_csv'),
    re_path(r'^labtest/ignore_set/$', views.ignore_code_set, name='ignore_code_set'),
    re_path(r'^labtest/map/(?P<native_code>.+)/$', views.map_native_code, name='map_native_code'),
    re_path(r'^labtest/unmapped/$', views.unmapped_labs_report, name='unmapped_labs_report'),
    re_path(r'^labtest/unmapped/(?P<condition>[\w\s]+)/$', views.unmapped_labs_report, name='condition_unmapped_labs_report'),
    #
    #-------------------------------------------------------------------------------
    # Nodis
    #-------------------------------------------------------------------------------
    #
    re_path(r'^cases/$', views.case_list, {'status': 'all'}, name='nodis_cases_all'),
    re_path(r'^cases/list/awaiting_review/$', views.case_list, {'status': 'await'}, name='nodis_cases_awaiting_review'),
    re_path(r'^cases/list/under_review/$', views.case_list, {'status': 'under'}, name='nodis_cases_under_review'),
    re_path(r'^cases/list/queued/$', views.case_list, {'status': 'queued'}, name='nodis_cases_queued'),
    re_path(r'^cases/list/sent/$', views.case_list, {'status': 'sent'}, name='nodis_cases_sent'),
    re_path(r'^cases/list/requeued/$', views.case_list, {'status': 'requeued'}, name='nodis_cases_requeued'),
    #
    # Case Detail
    #
    re_path(r'^cases/view/(?P<case_id>\d+)/$', views.case_detail, name='nodis_case_detail'),
    re_path(r'^cases/viewpert/(?P<case_id>\d+)/$', views.pertussis_detail, name='nodis_pertussis_detail'),
    re_path(r'^cases/update/(?P<case_id>\d+)/$', views.case_status_update, name='nodis_case_update'),
    re_path(r'^cases/transmit/(?P<case_id>\d+)/$', views.case_queue_for_transmit, name='nodis_case_transmit'),
    re_path(r'^provider/(?P<provider_id>\w+)/$', views.provider_detail, name='provider_detail'),
    re_path(r'^patient/(?P<patient_pk>\d+)/records/$', views.all_records, name='all_records'),
    #
    # Validator
    #
    re_path(r'^validate/$', views.validator_summary, name='validator_summary'),
    re_path(r'^validate/missing/$', views.validate_missing, name='validate_missing'),
    re_path(r'^validate/missing/case/(?P<result_id>\d+)/$', views.missing_case_detail, name='missing_case_detail'),
    re_path(r'^validate/new/$', views.validate_new, name='validate_new'),
    re_path(r'^validate/similar/$', views.validate_similar, name='validate_similar'),
    re_path(r'^validate/exact/$', views.validate_exact, name='validate_exact'),

]

ESP/urls.py
'''
URLs for entire ESP Health django project
'''
from django.urls import include, re_path
from django.conf.urls import include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView, LoginView
from ESP.settings import MEDIA_ROOT
from ESP.ui.views import status_page
from ESP.ui.views_survey import generate_survey_report, view_survey_report, survey_import
from django.views import static

class ExtraContextTemplateView(TemplateView):
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super(ExtraContextTemplateView, self).get_context_data(**kwargs)
        if self.extra_context:
            context.update(self.extra_context)
        return context

admin.autodiscover()

urlpatterns = [
    
    # Core Application
    re_path(r'^$', status_page, name='status'),
    
    # Vaers
    re_path(r'^vaers/', include('ESP.vaers.urls')),

    # HIV Risk 
    re_path(r'^hiv_risk/', include('ESP.hiv_risk.urls')),
    
    # Survey 
    re_path(r'^survey_import/', survey_import, name='survey_import'),
    re_path(r'^view_survey_report/', view_survey_report, name='view_survey_report'),
    re_path(r'^generate_survey_report/', generate_survey_report, name='generate_survey_report'),

    # Login and Logout
    #re_path(r'^login/?$', login, {'template_name': 'login.html'}, name='login'),
    #re_path(r'^logout/?$', logout, {'next_page': '/'}, name='logout'),
    re_path(r'^login/?$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    re_path(r'^logout/?$', LogoutView.as_view(), {'next_page': 'logged_out.hml'}, name='logout'),
    
    # About
    re_path(r'^about/', ExtraContextTemplateView.as_view(
        template_name='about.html',
        extra_context={'title': 'About ESP'}
    ), name='about'),
    
    
    # Django Admin
    re_path(r'^admin/', admin.site.urls),
#   (r'^admin/doc/', include('django.contrib.admindocs.urls'),

    re_path(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT}),
    
    # Configuration
    re_path(r'^conf/', include('ESP.conf.urls')),
    
    # Nodis
    #re_path(r'^nodis/', include('ESP.nodis.urls')),
    
    # Nodis
    re_path(r'^util/', include('ESP.ui.urls')),

    # cda_input
    re_path(r'^cda/', include('ESP.cda.urls')),

    # Continuity of Care
    re_path(r'^coc/', include('ESP.coc.urls')),

    #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #
    #re_path(r'^codes', code_maintenance),
    #re_path(r'^json_code_grid', json_code_grid, name='json_code_grid'),
    #re_path(r'^/$', include('ESP.ui.urls')),
]

ESP/vaers/urls.py
# -*- coding: utf-8 -*-

from django.urls import include, re_path

from ESP.vaers import views

app_name = 'vaers'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^casetable$', views.list_cases),
    re_path(r'^notify/(?P<id>\d+)/$', views.notify),
    re_path(r'^report$', views.report, name='report'),

    # Vaccine and Manufacturer Mapping
    re_path(r'^vaccines/', include('ESP.vaers.vaccine.urls')),
    
    # ptype can be digest or case.  digest takes a digest value for id, case takes a questionnaire id for id.
    re_path(r'^(?P<ptype>case|digest)/(?P<id>\w*)/$', views.case_details, name='present_case'),

    #line listing report
    re_path(r'^download/', views.download_vae_listing, name='download_listing'),    
]


ESP/cda/models.py
from django.db import models

# Create your models here.

ESP/conf/forms.py
'''
                              ESP Health Project
                             Configuration Module
                              User Interface Forms


@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


from django import forms


class CodeMappingForm(forms.Form):
    '''
    Form for mapping Native Code to LOINC
    '''
    native_name = forms.CharField(max_length=255, required=True)
    native_code = forms.CharField(max_length=100, required=True)

ESP/hiv_risk/forms.py
from django import forms
from django.db.models import BLANK_CHOICE_DASH
from ESP.emr.models import Provider
from ESP.hiv_risk.models import Static_Dispositions
from ESP.utils import log
from datetime import date, timedelta


class HRPDispositionForm(forms.Form):

    disposition = forms.ChoiceField(choices=BLANK_CHOICE_DASH, required=True)
    prep_date_provided = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), label='PrEP RX Started/Renewed Date (where applicable)', required=False)
    provider = forms.ChoiceField(label='Managing Provider', choices=BLANK_CHOICE_DASH, required=True)
    disposition_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), label='Disposition Date', required=True)
    comment = forms.CharField(widget=forms.Textarea, required=False)


    # Migrations will fail unless you build the choices in sub
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['disposition'].choices = BLANK_CHOICE_DASH + [(disposition.id, disposition.disposition_name) for disposition in Static_Dispositions.objects.all().order_by('sort_id')]

        #We only want providers that have been updated in the last year
        end_date = date.today() + timedelta(days=1)
        start_date = end_date- timedelta(days=365)

        self.fields['provider'].choices = BLANK_CHOICE_DASH + [(provider.id, provider.last_name +', ' + provider.first_name) for provider in Provider.objects.filter(provider_type=1) \
        .filter(updated_timestamp__range=[start_date, end_date]) \
        .exclude(last_name__isnull=True).order_by('last_name', 'first_name')]

ESP/cda/views.py
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.decorators import parser_classes 
from rest_framework.decorators import authentication_classes
from rest_framework.decorators import permission_classes
from rest_framework.response import Response
from rest_framework_xml.parsers import XMLParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from ESP.utils.utils import log
from ESP.settings import DATA_DIR
import datetime

# Create your views here.
@api_view(['POST'])
@parser_classes([XMLParser])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])

def post(request):

    try:
        # verify XML format
        if(request.content_type != 'application/xml'):
            return Response("Only XML accepted, Illegal type: " + request.content_type, 
                status=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE, content_type='text/plain')

        # get the patient id from the header
        patientId = ''
        try:
            patientId = request.META['HTTP_X_PATIENT_ID']
        except Exception as e:
            pass

        if(not patientId or len(patientId) < 6 or patientId.find('-') != -1):
            return Response("Missing or bad patient identifier (minimum length 6, dashes not allowed) 'x-patient-id' in header: [" + patientId +"]", 
                status=status.HTTP_417_EXPECTATION_FAILED, content_type='text/plain')
        
        # write the xml to a file under the data/cda structure
        try:
            file = None
            name = ''
            strXml = request.body.decode().strip()

            # check the contents to make sure at least appears to be XML
            length = len(strXml)
            if(length == 0):
                return Response("0 length file", status=status.HTTP_411_LENGTH_REQUIRED, content_type='text/plain')

            if(length < 5 or strXml[0:5].lower() != "<?xml"):
                return Response("Non-XML data", status=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE, content_type='text/plain')

            # create a file based on the username, current time and patient id
            dt = datetime.datetime.now()
            prefix = request.user.username[:8] + '-'
            log.debug('name:' + request.user.username)
            log.debug('prefix:' + prefix)
            name = prefix + dt.strftime('%Y%m%d-%H%M%S-%f') + '-' + patientId + '.xml'

            file = open(DATA_DIR + 'cda/incoming/' + name, "w")
            file.write(strXml)

        except Exception as e:
            msgErr = 'Exception creating local cda file: ' + name + '\n' + str(e)
            log.error(msgErr)
            return Response(msgErr, status=status.HTTP_417_EXPECTATION_FAILED, content_type='text/plain')
        
        finally:
            if file != None:
                file.close()

        return Response('received data:' + name, status=status.HTTP_200_OK, content_type='text/plain')

    except Exception as e:
        return Response(e.args[0], status=status.HTTP_400_BAD_REQUEST, content_type='text/plain')

ESP/conf/views.py
'''
                              ESP Health Project
Configuration Module
Views

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


import operator

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse
from django.shortcuts import render, redirect
from ESP.conf.models import IgnoredCode
from ESP.conf.models import LabTestMap
from ESP.utils.utils import log
from ESP.hef.base import BaseLabResultHeuristic, PrescriptionHeuristic, DiagnosisHeuristic
from ESP.ui.other_labs import STANDARD_LABS

@login_required
def heuristic_mapping_report(request):
    values = {'title': 'Abstract Lab Mapping Summary'}
    mapped = []
    unmapped = []
    test_names = []
    ## get all test names from heuristics and other labs
    lab_results = BaseLabResultHeuristic.get_all()
    for lrh in BaseLabResultHeuristic.get_all():
        test_names.append(lrh.test_name)
    for sname in STANDARD_LABS:
        if sname not in test_names:
            test_names.append(sname)

    for test_name in test_names: 
        maps = LabTestMap.objects.filter(test_name=test_name)
        if not maps:
            # if unmapped doesnt already have test name then add it
            if not unmapped.__contains__(test_name):
                unmapped.append( (test_name) )
            continue
        codes = maps.values_list('native_code', flat=True)
        # if mapped doesnt already contain (heuristic.test_name, codes) then add it
        # it is sorted already,for each in mapped get item compare with test name 
        # add first one
        if not mapped: mapped.append( (test_name, codes) )
        # loop through mapped make sure is not already there
        else:
            contains=False
            for index in range(len(mapped)):  
                if mapped.__getitem__(index).__contains__((test_name)):
                    contains=True
                    continue
            if not contains: 
                mapped.append( (test_name, codes) )              
        
    mapped.sort(key=operator.itemgetter(0))
    unmapped.sort()
    values['mapped'] = mapped
    values['unmapped'] = unmapped
    return render(request, 'conf/heuristic_mapping_report.html', values)

@login_required
def heuristic_reportables(request):
    values = {'title': 'Heuristic Reportables Summary'}
    
    reportable_rx = []
    reportable_dx = []
    reportable_lx = []
    
    for heuristic in BaseLabResultHeuristic.get_all():
        if heuristic.test_name not in reportable_lx:
            reportable_lx.append(heuristic.test_name)

    for sname in STANDARD_LABS:
        if sname not in reportable_lx:
            reportable_lx.append(sname)

    for heuristic in DiagnosisHeuristic.get_all():
        if isinstance(heuristic, DiagnosisHeuristic):
            for dx_code in heuristic.dx_code_queries:
                if dx_code not in reportable_dx:
                    reportable_dx.append(dx_code)
            
    for heuristic in PrescriptionHeuristic.get_all():
        if isinstance(heuristic, PrescriptionHeuristic):
            for drug in heuristic.drugs:
                if drug not in reportable_rx:
                    reportable_rx.append(drug)
    
    reportable_lx.sort()
    reportable_dx.sort(key=lambda x: x.verbose_name)
    reportable_rx.sort()
    
    values['reportable_lx'] = reportable_lx
    values['reportable_dx'] = reportable_dx
    values['reportable_rx'] = reportable_rx
    
    return render(request, 'conf/heuristic_reportables.html', values)


@user_passes_test(lambda u: u.is_staff)
def ignore_code(request, native_code):
    '''
    Display Unmapped Labs report generated from cache
    '''
    if request.method == 'POST':
        #ic_obj, created = IgnoredCode.objects.get_or_create(native_code=native_code.lower())
        ic_obj, created = IgnoredCode.objects.get_or_create(native_code=native_code) # Why was this lower() before?
        if created:
            ic_obj.save()
            msg = 'Native code "%s" has been added to the ignore list' % native_code
        else:
            msg = 'Native code "%s" is already on the ignore list' % native_code
        messages.add_message(request,messages.INFO,msg)
        log.debug(msg)
        return redirect(reverse('unmapped_labs_report'))
    else:
        values = {
            'title': 'Unmapped Lab Tests Report',
            "request":request,
            'native_code': native_code,
            }
        return render(request, 'conf/confirm_ignore_code.html', values)
    

ESP/templates/pages/vaers/collect_feedback.html
<div id="inp_case_comment">
  <div>{{ headline }}</div>
  <form id="frm_feedback" method="POST" action="{{ url }}">
    <textarea >{{ instructions }}</textarea>
    <input type="submit" value="Submit" />
   {% csrf_token %}
  </form>
</div>

ESP/templates/pages/vaers/identify.html
{% extends "vaers.html" %}
{% block content %}
<div>
    Please confirm that you are {{ case.patient.pcp.full_name }} 
    and that you are the care provider for {{ case.patient.full_name }}
    <div>
      <form action="{% url 'verify_case' case.digest %}" method="POST">
	<input type="hidden" value="{{ case.patient.pcp.id }}"/>
	<input type="radio" name="provider_confirmation" value="confirmed">Yes</input>
	<input type="radio" name="provider_confirmation" value="">No</input>
	<input type="submit" value="Submit" />
        {% csrf_token %}
      </form>
    </div>
</div>
{% endblock %}

ESP/templates/pages/vaers/manufacturers.html
{% extends "vaers.html" %}


{% block content %}
<div>
  <h1>Vaccine Manufacturer</h1>
  <div style="float:left;">
    <h2>Unmapped</h2>
    <table>
      {% for manufacturer in unmapped_manufacturers %}
      <tr>
	<td>{{manufacturer.name}}</td>
	<td><a href="{% url 'vaers.vaccine.views.manufacturer_detail' manufacturer.id %}">Edit</a></td>
      </tr>
      {% endfor %}    
    </table>
  </div>
  <div style="float:right;">
    <h2>Mapped</h2>
    <table>
      {% for manufacturer in mapped_manufacturers %}
      <tr>
	<td>{{manufacturer.name}}</td>
	<td>{{manufacturer.canonical_code}}</td>
      </tr>
      {% endfor %}
    </table>
  </div>

</div>

{% endblock %}

ESP/templates/pages/vaers/map_manufacturer.html
{% extends "vaers.html" %}
{% block content %}
{% if message %}<div class="warning">{{message}}</div>{% endif %}

<span>{{native_manufacturer.name}}</span>
<form method="post" action="{% url 'vaers.vaccine.views.manufacturer_detail' native_manufacturer.id %}">
  {{ form.as_p }}
  <button>Save</button>
  {% csrf_token %}
</form>
{% endblock %}

ESP/templates/pages/vaers/present.html
{% extends "vaers.html" %}
{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{{ site_css_folder }}vaers.css"/>
{% endblock %}
{% block extrascript %}

<script type="text/javascript" src="{{ site_javascript_folder }}vaers.js">

</script>

{% endblock%}

{% block content %}
<table border="0">
    <tr>
        <td style="border:0">
            <table id="tbl_case_details"
    <tr>
        <th align=left>Patient name <bR> [MRN]</th>
        <td>{{ case.patient.full_name }} <BR> [{{ case.patient.mrn }}]</td>
    </tr>
    <tr>
        <th align=left>Date of birth [age]</th>
        <td>{{ case.patient.date_of_birth|date:"d-M-Y" }}
            {% if case.patient.age.years > 2 %}
            [{{ case.patient.age.years }} years]
            {% else %}
            [{{ case.patient.age.months }} months]
            {% endif %}

        </td>
    </tr>
</table>
</td>
<td style="border:0">
    <table id="tbl_case_details">

        <tr>
            <th align=left>Reviewing Clinician</th>
            <td>{{ questionnaire.provider.full_name }}</td>
        </tr>
        <tr>
            <th align=left>Primary Care Provider</th>
            <td> {{ case.patient.pcp }}</td>
        </tr>

    </table>

</td>
</tr>
</table>
<BR>

<b>Your patient received the following vaccination on {{ case.date|date:"M d, Y"}}
    <br></b>
{% for vacc in case.immunizations.all %}
{{ vacc.name }}  <BR>
{% endfor %}
<br>
<b>We noted the following potentially concerning events after vaccination: </b>
<BR><BR>
<table border="0">
    <tr>
        <td style="border:0">
            <table border="0" id="tbl_case_details">
                <tr>
                    <th align=left>Event Date</th>
                    <th align=left>Days Since Vaccine(s) given</th>
                    <th align=left>Encounter Type</th>
                    <th align=left>Labs</th>
                    <th align=left>Diagnosis</th>
                    <th align=left>Prescription</th>
                    <th align=left>Allergies</th>
                </tr>
                <!-- add comments here
                -->

                {% for event in case.highest_event_category %}
                <tr>

                    {% ifequal content_type_enc event.content_type %}

                    <td> {{ event.content_object.date|date:"d-M-Y"}}</td>
                    <td> {{ event.gap }}</td>
                    <td> {% ifequal event.content_object.encounter_type 'VISIT' %}
                        Ambulatory
                        {% endifequal %}
                        {% ifequal event.content_object.encounter_type 'HOSPITALIZATION' %}
                        Hospitalized
                        {% endifequal %}
                        {% ifequal event.content_object.encounter_type 'ER' %}
                        ED
                        {% endifequal %}
                    <td></td>
                    <td> {{ event.matching_rule_explain }}</td>
                    </td>
                    <td></td>
                    <td></td>
                    {% endifequal %}

                    {% ifequal content_type_lx event.content_type %}

                    <td> {{event.content_object.date|date:"d-M-Y"}}</td>
                    <td> {{ event.gap }}</td>
                    <td></td>
                    <td> {{ event.content_object.native_name }} {{ event.content_object.result_float|default:"N/A"}} {{event.content_object.ref_unit|default:""}}
                        {% if event.last_known_value %}
                        <BR>(last value prior to vaccination {{ event.last_known_value }} on {{event.last_known_date|date:"d-M-Y" }})
                        {% endif %}
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>

                    {% endifequal %}

                    {% ifequal content_type_rx event.content_type %}
                    <td>{{ event.content_object.date|date:"d-M-Y" }}</td>
                    <td> {{ event.gap }}</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td> {{ event.content_object.matching_rule_explain }}</td>
                    <td></td>

                    {% endifequal %}

                    {% ifequal content_type_all event.content_type %}
                    <td> {{ event.content_object.date_noted|date:"d-M-Y" }}</td>
                    <td> {{ event.gap }}</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td> {{ event.content_object.name }}</td>

                    {% endifequal %}

                </tr>

                {% endfor %}

            </table>
        </td>
    </tr>
</table>
<BR>
{% if  case.prior_immunizations.all %}
<b>Note: the patient has also recently received the following vaccine(s):</b><BR>
{% for vacc in case.prior_immunizations.all %}
{{ vacc.date|date:"M d, Y"}} {{ vacc.name }} <BR>
{% endfor %}

{% endif %}
<form id="frm_case_confirmation" method="POST" action="{% url 'vaers:present_case' ptype formid  %}">
    <B>
        <div class="css_state">
            <header>
                <h2>
                    <label for="id_state_0">Possible Adverse Event?</label>
                </h2>
            </header>
            <div class="{% if form.state.errors %}warning{% endif %}" style="margin-left: 0px;">
                {% if form.state.errors %}
                <small>Please select one</small>
                {% endif %}
                {{ form.state }}
            </div>
            <div class="q" style="display: none;">
                <label for="{{ form.patient_recovered.id_for_label }}">{{ form.patient_recovered.label}}</label>
                {{ form.patient_recovered }}
            </div>
            <div class="q" style="display: none;">
                <h3>Result or outcome of adverse event(s): (Check all that apply)</h3>
                {{ form.result_visit }}
                <label for="{{ form.result_visit.id_for_label }}">{{ form.result_visit.label}}</label>
                <br/>
                {{ form.result_emergency }}
                <label for="{{ form.result_emergency.id_for_label }}">{{ form.result_emergency.label}}</label>
                <br/>
                {{ form.result_hosp }}
                <label for="{{ form.result_hosp.id_for_label }}">{{ form.result_hosp.label}}</label>
                <br/>
                <div style="padding-left:0px;">
                    <label for="{{ form.result_hosp_days.id_for_label }}">{{ form.result_hosp_days.label}}</label>
                    {{ form.result_hosp_days }}
                    <br/>
                    <label for="{{ form.result_hosp_name.id_for_label }}">{{ form.result_hosp_name.label}}</label>
                    {{ form.result_hosp_name }}
                    <br/>
                    <label for="{{ form.result_hosp_city.id_for_label }}">{{ form.result_hosp_city.label}}</label>
                    {{ form.result_hosp_city }}
                    <label for="{{ form.result_hosp_state.id_for_label }}">{{ form.result_hosp_state.label}}</label>
                    {{ form.result_hosp_state }}
                </div>
                <br/>
                {{ form.result_prolong }}
                <label for="{{ form.result_prolong.id_for_label }}">{{ form.result_prolong.label}}</label>
                <br/>
                {{ form.result_threat }}
                <label for="{{ form.result_threat.id_for_label }}">{{ form.result_threat.label}}</label>
                <br/>
                {{ form.result_disability }}
                <label for="{{ form.result_disability.id_for_label }}">{{ form.result_disability.label}}</label>
                <br/>
                {{ form.result_death }}
                <label for="{{ form.result_death.id_for_label }}">{{ form.result_death.label}}</label>
                --
                <label for="{{ form.result_death_date.id_for_label }}">{{ form.result_death_date.label}}</label>
                {{ form.result_death_date }}
                <br/>
                {{ form.result_congenital }}
                <label for="{{ form.result_congenital.id_for_label }}">{{ form.result_congenital.label}}</label>
                <br/>
                {{ form.result_unknown }}
                <label for="{{ form.result_unknown.id_for_label }}">{{ form.result_unknown.label}}</label>
                <br/>
                {{ form.result_none }}
                <label for="{{ form.result_none.id_for_label }}">{{ form.result_none.label}}</label>
            </div>
            <div class="q" style="display:none;">
                <label for="{{ form.event_comment.id_for_label}}">{{ form.event_comment.label}}</label>
                <br/>
                {{ form.event_comment }}
            </div>
        </div>
        <div class="css_ishelpful">
            <header>
                <h2>Please help us assess this automated adverse event reporting tool.</h2>
            </header>
            <div>
                <label for="{{ form.message_ishelpful.id_for_label }}">{{ form.message_ishelpful.label }}</label>
                {{ form.message_ishelpful }}
            </div>
            <div>
                <label for="{{ form.satisfaction_num_msg.id_for_label }}">{{ form.satisfaction_num_msg.label }}</label>
                {{ form.satisfaction_num_msg }}
            </div>
            <div>
                <label for="{{ form.assess_reporting.id_for_label }}">{{ form.assess_reporting.label }}</label>
                <br/>
                {{ form.assess_reporting }}
            </div>
        </div>

    </B>

    <input type="submit" value="submit"/>
    {% csrf_token %}
</form>
{% endblock %}