ESP/cda/urls.py
'''
                              ESP Health Project
User Interface Module
                               URL Configuration

@authors: Jay Boyer <jboyer@commoninf.com>
'''

from django.urls import include, re_path
from ESP.cda import views

urlpatterns = [
    re_path(r'^$', views.post),   
]

ESP/coc/urls.py
from django.urls import re_path
from ESP.coc import views

app_name = 'coc'

urlpatterns =[
    re_path(r'^linelist/$', views.linelist, name='linelist'),
]

ESP/hiv_risk/urls.py
# -*- coding: utf-8 -*-

from django.urls import include, re_path
from django.conf.urls import include
from ESP.hiv_risk import views
from django.urls import path

app_name = 'hiv_risk'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^report/view/(?P<patient_id>\d+)/$', views.hrp_detail, name='hrp_detail'),
    re_path(r'^report/$', views.report, name='report'),
    re_path(r'^show_file/$', views.show_file, name='show_file'),
    re_path(r'ad_hoc_disposition/$', views.ad_hoc_dispo, name='ad_hoc_disposition'),
    re_path(r'^ad_hoc_disposition/view/(?P<patient_id>\d+)/$', views.hrp_history_detail, name='hrp_history_detail'),
]

ESP/ui/urls.py
'''
                              ESP Health Project
User Interface Module
                               URL Configuration

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2010 Channing Laboratory
@license: LGPL
'''


from django.urls import include, re_path
from ESP.ui import views

urlpatterns = [
    re_path(r'^labtest/lookup/$', views.labtest_lookup, name='labtest_lookup'),
    re_path(r'^labtest/detail/$', views.labtest_detail, name='labtest_detail'),
    re_path(r'^labtest/linelist/(?P<native_code>.*)$', views.labtest_csv, name='labtest_csv'),
    re_path(r'^labtest/linelist/(?P<native_code>.*)$', views.labtest_csv, name='labtest_csv'),
    re_path(r'^labtest/ignore_set/$', views.ignore_code_set, name='ignore_code_set'),
    re_path(r'^labtest/map/(?P<native_code>.+)/$', views.map_native_code, name='map_native_code'),
    re_path(r'^labtest/unmapped/$', views.unmapped_labs_report, name='unmapped_labs_report'),
    re_path(r'^labtest/unmapped/(?P<condition>[\w\s]+)/$', views.unmapped_labs_report, name='condition_unmapped_labs_report'),
    #
    #-------------------------------------------------------------------------------
    # Nodis
    #-------------------------------------------------------------------------------
    #
    re_path(r'^cases/$', views.case_list, {'status': 'all'}, name='nodis_cases_all'),
    re_path(r'^cases/list/awaiting_review/$', views.case_list, {'status': 'await'}, name='nodis_cases_awaiting_review'),
    re_path(r'^cases/list/under_review/$', views.case_list, {'status': 'under'}, name='nodis_cases_under_review'),
    re_path(r'^cases/list/queued/$', views.case_list, {'status': 'queued'}, name='nodis_cases_queued'),
    re_path(r'^cases/list/sent/$', views.case_list, {'status': 'sent'}, name='nodis_cases_sent'),
    re_path(r'^cases/list/requeued/$', views.case_list, {'status': 'requeued'}, name='nodis_cases_requeued'),
    #
    # Case Detail
    #
    re_path(r'^cases/view/(?P<case_id>\d+)/$', views.case_detail, name='nodis_case_detail'),
    re_path(r'^cases/viewpert/(?P<case_id>\d+)/$', views.pertussis_detail, name='nodis_pertussis_detail'),
    re_path(r'^cases/update/(?P<case_id>\d+)/$', views.case_status_update, name='nodis_case_update'),
    re_path(r'^cases/transmit/(?P<case_id>\d+)/$', views.case_queue_for_transmit, name='nodis_case_transmit'),
    re_path(r'^provider/(?P<provider_id>\w+)/$', views.provider_detail, name='provider_detail'),
    re_path(r'^patient/(?P<patient_pk>\d+)/records/$', views.all_records, name='all_records'),
    #
    # Validator
    #
    re_path(r'^validate/$', views.validator_summary, name='validator_summary'),
    re_path(r'^validate/missing/$', views.validate_missing, name='validate_missing'),
    re_path(r'^validate/missing/case/(?P<result_id>\d+)/$', views.missing_case_detail, name='missing_case_detail'),
    re_path(r'^validate/new/$', views.validate_new, name='validate_new'),
    re_path(r'^validate/similar/$', views.validate_similar, name='validate_similar'),
    re_path(r'^validate/exact/$', views.validate_exact, name='validate_exact'),

]

ESP/urls.py
'''
URLs for entire ESP Health django project
'''
from django.urls import include, re_path
from django.conf.urls import include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView, LoginView
from ESP.settings import MEDIA_ROOT
from ESP.ui.views import status_page
from ESP.ui.views_survey import generate_survey_report, view_survey_report, survey_import
from django.views import static

class ExtraContextTemplateView(TemplateView):
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super(ExtraContextTemplateView, self).get_context_data(**kwargs)
        if self.extra_context:
            context.update(self.extra_context)
        return context

admin.autodiscover()

urlpatterns = [
    
    # Core Application
    re_path(r'^$', status_page, name='status'),
    
    # Vaers
    re_path(r'^vaers/', include('ESP.vaers.urls')),

    # HIV Risk 
    re_path(r'^hiv_risk/', include('ESP.hiv_risk.urls')),
    
    # Survey 
    re_path(r'^survey_import/', survey_import, name='survey_import'),
    re_path(r'^view_survey_report/', view_survey_report, name='view_survey_report'),
    re_path(r'^generate_survey_report/', generate_survey_report, name='generate_survey_report'),

    # Login and Logout
    #re_path(r'^login/?$', login, {'template_name': 'login.html'}, name='login'),
    #re_path(r'^logout/?$', logout, {'next_page': '/'}, name='logout'),
    re_path(r'^login/?$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    re_path(r'^logout/?$', LogoutView.as_view(), {'next_page': 'logged_out.hml'}, name='logout'),
    
    # About
    re_path(r'^about/', ExtraContextTemplateView.as_view(
        template_name='about.html',
        extra_context={'title': 'About ESP'}
    ), name='about'),
    
    
    # Django Admin
    re_path(r'^admin/', admin.site.urls),
#   (r'^admin/doc/', include('django.contrib.admindocs.urls'),

    re_path(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT}),
    
    # Configuration
    re_path(r'^conf/', include('ESP.conf.urls')),
    
    # Nodis
    #re_path(r'^nodis/', include('ESP.nodis.urls')),
    
    # Nodis
    re_path(r'^util/', include('ESP.ui.urls')),

    # cda_input
    re_path(r'^cda/', include('ESP.cda.urls')),

    # Continuity of Care
    re_path(r'^coc/', include('ESP.coc.urls')),

    #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #
    #re_path(r'^codes', code_maintenance),
    #re_path(r'^json_code_grid', json_code_grid, name='json_code_grid'),
    #re_path(r'^/$', include('ESP.ui.urls')),
]

ESP/conf/forms.py
'''
                              ESP Health Project
                             Configuration Module
                              User Interface Forms


@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


from django import forms


class CodeMappingForm(forms.Form):
    '''
    Form for mapping Native Code to LOINC
    '''
    native_name = forms.CharField(max_length=255, required=True)
    native_code = forms.CharField(max_length=100, required=True)

ESP/hiv_risk/forms.py
from django import forms
from django.db.models import BLANK_CHOICE_DASH
from ESP.emr.models import Provider
from ESP.hiv_risk.models import Static_Dispositions
from ESP.utils import log
from datetime import date, timedelta


class HRPDispositionForm(forms.Form):

    disposition = forms.ChoiceField(choices=BLANK_CHOICE_DASH, required=True)
    prep_date_provided = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), label='PrEP RX Started/Renewed Date (where applicable)', required=False)
    provider = forms.ChoiceField(label='Managing Provider', choices=BLANK_CHOICE_DASH, required=True)
    disposition_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), label='Disposition Date', required=True)
    comment = forms.CharField(widget=forms.Textarea, required=False)


    # Migrations will fail unless you build the choices in sub
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['disposition'].choices = BLANK_CHOICE_DASH + [(disposition.id, disposition.disposition_name) for disposition in Static_Dispositions.objects.all().order_by('sort_id')]

        #We only want providers that have been updated in the last year
        end_date = date.today() + timedelta(days=1)
        start_date = end_date- timedelta(days=365)

        self.fields['provider'].choices = BLANK_CHOICE_DASH + [(provider.id, provider.last_name +', ' + provider.first_name) for provider in Provider.objects.filter(provider_type=1) \
        .filter(updated_timestamp__range=[start_date, end_date]) \
        .exclude(last_name__isnull=True).order_by('last_name', 'first_name')]

ESP/vaers/vaccine/forms.py
from django import forms

from ESP.conf.models import Vaccine, ImmunizationManufacturer

try:
    STANDARD_VACCINES = ((x.code, str(x)) for x in Vaccine.acceptable_mapping_values())
except:
    STANDARD_VACCINES = []
try:
    STANDARD_MANUFACTURERS = ((x.code, str(x)) for x in ImmunizationManufacturer.objects.all())
except:
    STANDARD_MANUFACTURERS = []

class StandardVaccinesForm(forms.Form):
    vaccine = forms.ChoiceField(choices=STANDARD_VACCINES)

class StandardManufacturersForm(forms.Form):
    manufacturer = forms.ChoiceField(choices=STANDARD_MANUFACTURERS)

ESP/cda/views.py
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.decorators import parser_classes 
from rest_framework.decorators import authentication_classes
from rest_framework.decorators import permission_classes
from rest_framework.response import Response
from rest_framework_xml.parsers import XMLParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from ESP.utils.utils import log
from ESP.settings import DATA_DIR
import datetime

# Create your views here.
@api_view(['POST'])
@parser_classes([XMLParser])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])

def post(request):

    try:
        # verify XML format
        if(request.content_type != 'application/xml'):
            return Response("Only XML accepted, Illegal type: " + request.content_type, 
                status=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE, content_type='text/plain')

        # get the patient id from the header
        patientId = ''
        try:
            patientId = request.META['HTTP_X_PATIENT_ID']
        except Exception as e:
            pass

        if(not patientId or len(patientId) < 6 or patientId.find('-') != -1):
            return Response("Missing or bad patient identifier (minimum length 6, dashes not allowed) 'x-patient-id' in header: [" + patientId +"]", 
                status=status.HTTP_417_EXPECTATION_FAILED, content_type='text/plain')
        
        # write the xml to a file under the data/cda structure
        try:
            file = None
            name = ''
            strXml = request.body.decode().strip()

            # check the contents to make sure at least appears to be XML
            length = len(strXml)
            if(length == 0):
                return Response("0 length file", status=status.HTTP_411_LENGTH_REQUIRED, content_type='text/plain')

            if(length < 5 or strXml[0:5].lower() != "<?xml"):
                return Response("Non-XML data", status=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE, content_type='text/plain')

            # create a file based on the username, current time and patient id
            dt = datetime.datetime.now()
            prefix = request.user.username[:8] + '-'
            log.debug('name:' + request.user.username)
            log.debug('prefix:' + prefix)
            name = prefix + dt.strftime('%Y%m%d-%H%M%S-%f') + '-' + patientId + '.xml'

            file = open(DATA_DIR + 'cda/incoming/' + name, "w")
            file.write(strXml)

        except Exception as e:
            msgErr = 'Exception creating local cda file: ' + name + '\n' + str(e)
            log.error(msgErr)
            return Response(msgErr, status=status.HTTP_417_EXPECTATION_FAILED, content_type='text/plain')
        
        finally:
            if file != None:
                file.close()

        return Response('received data:' + name, status=status.HTTP_200_OK, content_type='text/plain')

    except Exception as e:
        return Response(e.args[0], status=status.HTTP_400_BAD_REQUEST, content_type='text/plain')

ESP/conf/views.py
'''
                              ESP Health Project
Configuration Module
Views

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


import operator

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse
from django.shortcuts import render, redirect
from ESP.conf.models import IgnoredCode
from ESP.conf.models import LabTestMap
from ESP.utils.utils import log
from ESP.hef.base import BaseLabResultHeuristic, PrescriptionHeuristic, DiagnosisHeuristic
from ESP.ui.other_labs import STANDARD_LABS

@login_required
def heuristic_mapping_report(request):
    values = {'title': 'Abstract Lab Mapping Summary'}
    mapped = []
    unmapped = []
    test_names = []
    ## get all test names from heuristics and other labs
    lab_results = BaseLabResultHeuristic.get_all()
    for lrh in BaseLabResultHeuristic.get_all():
        test_names.append(lrh.test_name)
    for sname in STANDARD_LABS:
        if sname not in test_names:
            test_names.append(sname)

    for test_name in test_names: 
        maps = LabTestMap.objects.filter(test_name=test_name)
        if not maps:
            # if unmapped doesnt already have test name then add it
            if not unmapped.__contains__(test_name):
                unmapped.append( (test_name) )
            continue
        codes = maps.values_list('native_code', flat=True)
        # if mapped doesnt already contain (heuristic.test_name, codes) then add it
        # it is sorted already,for each in mapped get item compare with test name 
        # add first one
        if not mapped: mapped.append( (test_name, codes) )
        # loop through mapped make sure is not already there
        else:
            contains=False
            for index in range(len(mapped)):  
                if mapped.__getitem__(index).__contains__((test_name)):
                    contains=True
                    continue
            if not contains: 
                mapped.append( (test_name, codes) )              
        
    mapped.sort(key=operator.itemgetter(0))
    unmapped.sort()
    values['mapped'] = mapped
    values['unmapped'] = unmapped
    return render(request, 'conf/heuristic_mapping_report.html', values)

@login_required
def heuristic_reportables(request):
    values = {'title': 'Heuristic Reportables Summary'}
    
    reportable_rx = []
    reportable_dx = []
    reportable_lx = []
    
    for heuristic in BaseLabResultHeuristic.get_all():
        if heuristic.test_name not in reportable_lx:
            reportable_lx.append(heuristic.test_name)

    for sname in STANDARD_LABS:
        if sname not in reportable_lx:
            reportable_lx.append(sname)

    for heuristic in DiagnosisHeuristic.get_all():
        if isinstance(heuristic, DiagnosisHeuristic):
            for dx_code in heuristic.dx_code_queries:
                if dx_code not in reportable_dx:
                    reportable_dx.append(dx_code)
            
    for heuristic in PrescriptionHeuristic.get_all():
        if isinstance(heuristic, PrescriptionHeuristic):
            for drug in heuristic.drugs:
                if drug not in reportable_rx:
                    reportable_rx.append(drug)
    
    reportable_lx.sort()
    reportable_dx.sort(key=lambda x: x.verbose_name)
    reportable_rx.sort()
    
    values['reportable_lx'] = reportable_lx
    values['reportable_dx'] = reportable_dx
    values['reportable_rx'] = reportable_rx
    
    return render(request, 'conf/heuristic_reportables.html', values)


@user_passes_test(lambda u: u.is_staff)
def ignore_code(request, native_code):
    '''
    Display Unmapped Labs report generated from cache
    '''
    if request.method == 'POST':
        #ic_obj, created = IgnoredCode.objects.get_or_create(native_code=native_code.lower())
        ic_obj, created = IgnoredCode.objects.get_or_create(native_code=native_code) # Why was this lower() before?
        if created:
            ic_obj.save()
            msg = 'Native code "%s" has been added to the ignore list' % native_code
        else:
            msg = 'Native code "%s" is already on the ignore list' % native_code
        messages.add_message(request,messages.INFO,msg)
        log.debug(msg)
        return redirect(reverse('unmapped_labs_report'))
    else:
        values = {
            'title': 'Unmapped Lab Tests Report',
            "request":request,
            'native_code': native_code,
            }
        return render(request, 'conf/confirm_ignore_code.html', values)
    

ESP/templates/pages/hiv_risk/ad_hoc_disposition.html
{% extends "hiv_risk.html" %}
{% load django_tables2 %}



{% block extrastyle %}

    <style type="text/css" media="all">
        form ol {
            list-style: none;
        }

        #search_div {
            float: left;
        }

        #summary_div {
            float: right;
        }

        #form_table {
            border: 0;
        }

        #form_table th {
            text-align: right;
            border: 0;
        }

        #form_table td {
            text-align: left;
            border: 0;
        }
    </style>

{% endblock %}


{% block content %}

    <div id="search_div">
        <h2>Search</h2>

        <form id="search_form" method="GET" action="{% url 'hiv_risk:ad_hoc_disposition' %}">

            <table id="form_table">
                {{ search_form.as_table }}
            </table>
            <p>
                <input type="submit" value="Search Results"/>
		<button type="button">
                    <a href="{{ clear_search_path }}">Reset Search</a>
		</button>

            </p>
        </form>
    </div>

    <div style="clear:both;"/>

    <h2>Risk for Acquisition of HIV - Historical Patient List</h2>

    {% render_table table 'table.html' %}


{% endblock %}

ESP/templates/pages/hiv_risk/ad_hoc_disposition_view_update.html
{% extends "hiv_risk.html" %}
{% load django_tables2 %}


{% block extrastyle %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ site_javascript_folder }}/flexigrid/css/flexigrid/flexigrid.css" />
    <style type="text/css">
    table {
        border-width: thin;
        border-spacing: 0;
        border-style: solid;
        border-color: gray;
        border-collapse: separate;
        background-color: white;
    }
    table th {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    table td {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    </style>
{% endblock %}


{% block content %}

<h2>
    Patient Information
</h2>

<table id="patient_info">
    <tr>
        <th>ESP Patient Id</th>
        <th>Patient MRN</th>
        <th>Patient Last Name</th>
        <th>Patient First Name</th>
	<th>Patient Phone</th>
        <th>Gender</th>
        <th>Current Age</th>
        <th>Ethnicity</th>
        <th>Race</th>
        <th>Home Language</th>
        <th>PCP</th>
    </tr>
    <tr>
        <td>{{ hrp_history.patient_id }}</td>
        <td>{{ mrn }}</td>
        <td>{{ last_name }}</td>
        <td>{{ first_name }}</td>
	<td>{{ telephone }}</td>
        <td>{{ gender }}</td>
        <td>{{ current_age }}</td>
        <td>{{ ethnicity }}</td>
        <td>{{ race }}</td>
        <td>{{ home_language }}</td>
	<td>{{ pcp_name }}</td>
    </tr>
</table>


<h2>
   Disposition History 
</h2>

<table id="disposition_history">
    <tr>
      <th>Disposition</th>
      <th>Date</th>
      <th>Clinician</th>
      <th>PrEP RX Date</th>
      <th>Recorded By User</th>
      <th>Comment</th>
    </tr>
    {% for item in dispo_hist %}
      <tr>
	<td>{{ item.disposition.disposition_name }}</td> 
        <td>{{ item.disposition_date }}</td>
	<td>{{ item.managing_provider.last_name }}, {{ item.managing_provider.first_name }}</td>
	<td>{{ item.prep_date_entered }}</td>
	<td>{{ item.created_by_user }}</td>
	<td>{{ item.comment }}</td>
      </tr>
    {% endfor %}
  </table>


&nbsp;
&nbsp;
<hr>


<h2>PrEP Engagement Disposition</h2>
    <form method="POST" action="{% url 'hiv_risk:hrp_history_detail' patient_id %}?return={{condition}}">

    {{ form.as_p }}
    <p>
        <input type="submit" value="SUBMIT">
    </p>
    {% csrf_token %}
</form>

<button type="button">
    <a href="{% url 'hiv_risk:show_file' %}" target="_blank">View Disposition Definitions Document</a>
</button>


<hr>

{% endblock %}

ESP/templates/pages/hiv_risk/hrp_detail_view_update.html
{% extends "hiv_risk.html" %}
{% load django_tables2 %}


{% block extrastyle %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ site_javascript_folder }}/flexigrid/css/flexigrid/flexigrid.css" />
    <style type="text/css">
    table {
        border-width: thin;
        border-spacing: 0;
        border-style: solid;
        border-color: gray;
        border-collapse: separate;
        background-color: white;
    }
    table th {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    table td {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    </style>
{% endblock %}


{% block content %}

<h2>HIV Risk Score: {{ hrp.hiv_risk_score }} </h2>

<h2>
    Patient Information
</h2>

<table id="patient_info">
    <tr>
        <th>ESP Patient Id</th>
        <th>Patient MRN</th>
        <th>Patient Last Name</th>
        <th>Patient First Name</th>
	<th>Patient Phone</th>
        <th>Gender</th>
        <th>Current Age</th>
        <th>Ethnicity</th>
        <th>Race</th>
        <th>Home Language</th>
        <th>PCP</th>
	<th>PCP Dept</th>
    </tr>
    <tr>
        <td>{{ hrp.patient_id }}</td>
        <td>{{ mrn }}</td>
        <td>{{ last_name }}</td>
        <td>{{ first_name }}</td>
	<td>{{ telephone }}</td>
        <td>{{ gender }}</td>
        <td>{{ current_age }}</td>
        <td>{{ ethnicity }}</td>
        <td>{{ race }}</td>
        <td>{{ home_language }}</td>
	<td>{{ pcp_name }}</td>
	<td>{{ pcp_dept }}</td>
    </tr>
</table>

<h2>
  PrEP Details 
</h2>

<table id="prep_info">
    <tr>
        <th>Previous PrEP Order</th>
        <th>Last PrEP Order Date</th>
    </tr>
    <tr>
        <td>{{ hrp.previous_prep_order }}</td>
        <td>{{ hrp.last_prep_order_date }}</td>
    </tr>
</table>


<h2>
   Highest Risk Factors 
</h2>

<table id="highest_risk_var">
    <tr>
        <th>Highest Risk Factor</th>
        <th>Second Highest Risk Factor</th>
    </tr>
    <tr>
        <td>{{ hrp.highest_risk_variable }}</td>
        <td>{{ hrp.second_highest_risk_variable }}</td>
    </tr>
</table>

<h2>
   Selected Risk Factor Information
</h2>

<table id="risk_variables">
    <tr>    
        <th>Suboxone Last 2 Yrs</th>
        <th>STD Case Last 2 Yrs</th>
        <th>Suboxone & STD Last 2 Yrs
        <th>Illicit Drug Use Last 2 Yrs</th>
        <th>Sexually Active Status</th>
        <th># Positive Gonorrhea Tests Last 2 Yrs</th>
        <th># HIV Test Dates Last 2 Yrs</th>
        <th>Last HIV Test Date</th>
        <th>Bicillin 2.4 MU injection Last 2 Yrs</th>
        <th>Syphilis Dx Last 2 Yrs</th> 
        <th>Syphilis Dx Name Last 2 Yrs</th>
        <th>Sex Partner Gender</th>

    </tr>
    <tr>
        <td>{{ hrp.suboxone_last_2yr }}</td>
        <td>{{ hrp.std_case_last_2yr }}</td>
        <td>{{ hrp.suboxone_and_std_last_2yr }}</td>
        <td>{{ hrp.ill_drug_use_last_2yr }}</td>
        <td>{{ hrp.sexually_active_status }}</td>
        <td>{{ hrp.num_pos_gon_tests_last_2yr }}</td>
        <td>{{ hrp.num_hiv_tst_dates_last_2yr }}</td>
        <td>{{ hrp.last_hiv_test_date }}</td>
        <td>{{ hrp.bicillin_24_inj_last_2yr }}</td>
        <td>{{ hrp.syph_dx_last_2yr }}</td>
        <td>{{ hrp.syph_dx_name_last_2yr }}</td>
        <td>{{ hrp.sex_partner_gender }}</td>
    </tr>
</table>

<h2>
   Mpox Vaccine Information
</h2>

<table id="mpox_info">
    <tr>
        <th>Last Mpox Vaccine Date</th>
	<th>Number of Mpox Vaccines Administered</th>
    </tr>
    <tr>
        <td>{{ hrp.last_mpox_vax_date }}</td>
	<td>{{ hrp.num_mpox_vax }}</td>
    </tr>
</table>

<h2>
    Doxycycline Rx Information
</h2>

<table id="doxy_info">
    <tr>
        <th>Last Doxycycline Rx Date</th>
    </tr>
    <tr>
        <td>{{ hrp.last_doxy_rx_date }}</td>
    </tr>
</table>





<h2>
   Disposition History 
</h2>

<table id="disposition_history">
    <tr>
      <th>Disposition</th>
      <th>Date</th>
      <th>Clinician</th>
      <th>PrEP RX Date</th>
      <th>Recorded By User</th>
      <th>Comment</th>
    </tr>
    {% for item in dispo_hist %}
      <tr>
	<td>{{ item.disposition.disposition_name }}</td> 
        <td>{{ item.disposition_date }}</td>
	<td>{{ item.managing_provider.last_name }}, {{ item.managing_provider.first_name }}</td>
	<td>{{ item.prep_date_entered }}</td>
	<td>{{ item.created_by_user }}</td>
	<td>{{ item.comment }}</td>
      </tr>
    {% endfor %}
  </table>


&nbsp;
&nbsp;
<hr>


<h2>PrEP Engagement Disposition</h2>
    <form method="POST" action="{% url 'hiv_risk:hrp_detail' patient_id %}?return={{condition}}">

    {{ form.as_p }}
    <p>
        <input type="submit" value="SUBMIT">
    </p>
    {% csrf_token %}
</form>

<button type="button">
    <a href="{% url 'hiv_risk:show_file' %}" target="_blank">View Disposition Definitions Document</a>
</button>


<hr>

{% endblock %}